import express from "express";
import connectDb from "./connect-db.js";
import cors from "cors";
import foodRouter from "./routers/food.router.js";
import foodCategoryRouter from "./routers/food-category.router.js";
import { getGroupFoods } from "./controllers/foodGroupCategory.js";
import userRouter from "./routers/user.router.js";
import foodOrderRouter from "./routers/foodorder.router.js";
const app = express();
const PORT = 3001;
app.use(cors());
app.use(express.json());
connectDb();
app.use("/", foodRouter);
app.use("/", foodCategoryRouter);
app.use("/", userRouter);
app.use("/", foodOrderRouter);
app.use("/categories", getGroupFoods);
app.listen(PORT, () => {
  console.log("amjilttai holbogdloo");
});
